[project]
name = "schedule-api"
version = "0.1.0"
description = "API для получения расписания из google таблицы."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff.lint]
select = ["ALL"]
